services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Users:
    class: App\Admin\UsersAdmin
    arguments: [ ~, App\Entity\Users, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Users, group: Users }

  Sanction:
    class: App\Admin\SanctionAdmin
    arguments: [ ~, App\Entity\Sanction, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Sanction, group: Sanction }

  Tournament:
    class: App\Admin\TournamentAdmin
    arguments: [ ~, App\Entity\Tournament, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Tournament, group: Tournament }

  Teams:
    class: App\Admin\TeamsAdmin
    arguments: [ ~, App\Entity\Teams, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Teams, group: Teams }

  Type:
    class: App\Admin\TypeAdmin
    arguments: [ ~, App\Entity\Type, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Type, group: Type }

  Report:
    class: App\Admin\ReportAdmin
    arguments: [ ~, App\Entity\Report, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Report, group: Report }