admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /
    host: 'admin.%base_host%'

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /
    host: 'admin.%base_host%'

admin_security:
    resource: '../../src/Controller/Admin'
    host: 'admin.%base_host%'
    type: annotation
