monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

        swift:
            type:   swift_mailer
            from_email: '%env(MONOLOG_FROM_EMAIL)%'
            to_email:   '%env(MONOLOG_TO_EMAIL)%'
            subject:    '%env(MONOLOG_EMAIL_SUBJECT)%'
            level:  error