version: "3.7"

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: tool-nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./proxy.conf:/etc/nginx/proxy.conf

networks:
    default:
        external:
            name: nginx-proxy
